# Generated by Django 4.0.5 on 2022-06-26 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.FileField(upload_to='product/image', verbose_name='썸네일')),
                ('description', models.TextField(verbose_name='설명')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('exposure_start_date', models.DateField(verbose_name='노출 시작일')),
                ('exposure_end_date', models.DateField(verbose_name='노출 종료일자')),
                ('is_active', models.BooleanField(verbose_name='활성화여부')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created', models.DateField(auto_now_add=True, verbose_name='등록시간')),
                ('rating', models.IntegerField(verbose_name='평점')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='상품')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
