# Generated by Django 4.0.5 on 2022-06-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exposure_end_date',
            field=models.DateField(null=True, verbose_name='노출 종료 일자'),
        ),
        migrations.AddField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateField(null=True, verbose_name='노출 시작 일자'),
        ),
    ]
